name: Build & publish blog

on:
  push:
    branches: ["master"]

jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check permissions
        run: ls -l ${{ github.workspace }}

      - name: Build Site
        run: docker run --rm --volume ${{ github.workspace }}:/home/hugo jakepricedev/docker-hugo:0.101.0

